//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSU_360_X.Resources.Views.Section1Personal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSU_360_X.Resources.Views.Section1Personal.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Policy.
        /// </summary>
        public static string AcademicPolicy {
            get {
                return ResourceManager.GetString("AcademicPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Rank.
        /// </summary>
        public static string AcademicRank {
            get {
                return ResourceManager.GetString("AcademicRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Focused.
        /// </summary>
        public static string AdministrationFocused {
            get {
                return ResourceManager.GetString("AdministrationFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary responsibility is departmental or university management..
        /// </summary>
        public static string AdministrationFocusedDesc {
            get {
                return ResourceManager.GetString("AdministrationFocusedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Academic Year for Research Track.
        /// </summary>
        public static string ApprovedAcademicYear {
            get {
                return ResourceManager.GetString("ApprovedAcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty if not applicable or not yet approved..
        /// </summary>
        public static string ApprovedAcademicYearDesc {
            get {
                return ResourceManager.GetString("ApprovedAcademicYearDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Sections.
        /// </summary>
        public static string EvaluationSections {
            get {
                return ResourceManager.GetString("EvaluationSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Member.
        /// </summary>
        public static string FacultyMember {
            get {
                return ResourceManager.GetString("FacultyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 Rangsit University. All academic rights reserved..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Degree.
        /// </summary>
        public static string HighestDegree {
            get {
                return ResourceManager.GetString("HighestDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Profile.
        /// </summary>
        public static string PersonalProfile {
            get {
                return ResourceManager.GetString("PersonalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Focused.
        /// </summary>
        public static string ResearchFocused {
            get {
                return ResourceManager.GetString("ResearchFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary responsibility is academic research and publication..
        /// </summary>
        public static string ResearchFocusedDesc {
            get {
                return ResourceManager.GetString("ResearchFocusedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information and work focus configuration..
        /// </summary>
        public static string Section1Description {
            get {
                return ResourceManager.GetString("Section1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 1: General Info.
        /// </summary>
        public static string Section1GeneralInfo {
            get {
                return ResourceManager.GetString("Section1GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 2: Teaching.
        /// </summary>
        public static string Section2Teaching {
            get {
                return ResourceManager.GetString("Section2Teaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 3: Services &amp; Duties.
        /// </summary>
        public static string Section3ServicesDuties {
            get {
                return ResourceManager.GetString("Section3ServicesDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 4: Research.
        /// </summary>
        public static string Section4Research {
            get {
                return ResourceManager.GetString("Section4Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Evaluation System.
        /// </summary>
        public static string StaffEvaluationSystem {
            get {
                return ResourceManager.GetString("StaffEvaluationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary &amp; Submit.
        /// </summary>
        public static string SummarySubmit {
            get {
                return ResourceManager.GetString("SummarySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Desk.
        /// </summary>
        public static string SupportDesk {
            get {
                return ResourceManager.GetString("SupportDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Focused.
        /// </summary>
        public static string TeachingFocused {
            get {
                return ResourceManager.GetString("TeachingFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary responsibility is instruction and student mentorship..
        /// </summary>
        public static string TeachingFocusedDesc {
            get {
                return ResourceManager.GetString("TeachingFocusedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Progress.
        /// </summary>
        public static string TotalProgress {
            get {
                return ResourceManager.GetString("TotalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Documentation.
        /// </summary>
        public static string UserDocumentation {
            get {
                return ResourceManager.GetString("UserDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Focus Configuration.
        /// </summary>
        public static string WorkFocusConfiguration {
            get {
                return ResourceManager.GetString("WorkFocusConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
