//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSU_360_X.Resources.Views.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSU_360_X.Resources.Views.Employee.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to digital libraries, research databases, LMS, and teaching materials..
        /// </summary>
        public static string AcademicResourcesDesc {
            get {
                return ResourceManager.GetString("AcademicResourcesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Resources.
        /// </summary>
        public static string AcademicResourcesTitle {
            get {
                return ResourceManager.GetString("AcademicResourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access e-Document systems, leave requests, room booking, and general administrative forms..
        /// </summary>
        public static string AdminWorkDesc {
            get {
                return ResourceManager.GetString("AdminWorkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Work.
        /// </summary>
        public static string AdminWorkTitle {
            get {
                return ResourceManager.GetString("AdminWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for university cultural events, submit activity logs, and view upcoming art exhibitions..
        /// </summary>
        public static string ArtsCultureDesc {
            get {
                return ResourceManager.GetString("ArtsCultureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts &amp; Culture.
        /// </summary>
        public static string ArtsCultureTitle {
            get {
                return ResourceManager.GetString("ArtsCultureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track special assignments, committee responsibilities, and ad-hoc projects assigned by the dean..
        /// </summary>
        public static string AssignedTasksDesc {
            get {
                return ResourceManager.GetString("AssignedTasksDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Tasks.
        /// </summary>
        public static string AssignedTasksTitle {
            get {
                return ResourceManager.GetString("AssignedTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your academic and administrative tasks efficiently..
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Dashboard.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review staff performance metrics, approve evaluation forms, and manage departmental KPIs..
        /// </summary>
        public static string EvalReviewDesc {
            get {
                return ResourceManager.GetString("EvalReviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Review.
        /// </summary>
        public static string EvalReviewTitle {
            get {
                return ResourceManager.GetString("EvalReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 Rangsit University. Intelligent Experience..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your self-assessment report, teaching portfolio, and research contributions for the year..
        /// </summary>
        public static string PerformanceEvalDesc {
            get {
                return ResourceManager.GetString("PerformanceEvalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Eval.
        /// </summary>
        public static string PerformanceEvalTitle {
            get {
                return ResourceManager.GetString("PerformanceEvalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report facility issues, request IT support, and access campus maintenance services..
        /// </summary>
        public static string SupportTasksDesc {
            get {
                return ResourceManager.GetString("SupportTasksDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Tasks.
        /// </summary>
        public static string SupportTasksTitle {
            get {
                return ResourceManager.GetString("SupportTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage document processing for international staff work permits and student visas..
        /// </summary>
        public static string VisaReviewDesc {
            get {
                return ResourceManager.GetString("VisaReviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Review.
        /// </summary>
        public static string VisaReviewTitle {
            get {
                return ResourceManager.GetString("VisaReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
